export const DataTableData = [
  {
    id: 0,
    Compaigns: " Facewash",
    Clicks: 24,
    cost: "USD 100",
    company: "BUZZWORKS",
    conversions: "17",
    revenue: "$2,570.39",
  },
  {
    id: 1,
    Compaigns: "Shampoo ",
    Clicks: 40,
    cost: "USD 200",
    company: "MARQET",
    conversions: "14",
    revenue: "$1,488.76",
  },
  {
    id: 2,
    Compaigns: "Toothpaste ",
    Clicks: 21,
    cost: "USD 300",
    company: "OBONES",
    conversions: "28",
    revenue: "$1,336.93",
  },
  {
    id: 3,
    Compaigns: " Body Lotion",
    Clicks: 30,
    cost: "USD 400",
    company: "SLUMBERIA",
    conversions: "08",
    revenue: "$2,156.70",
  },
  {
    id: 4,
    Compaigns: "Deodorant ",
    Clicks: 20,
    cost: "USD 500",
    company: "ESCENTA",
    conversions: "12",
    revenue: "$3,057.42",
  },
  {
    id: 5,
    Compaigns: " Laundry Detergent",
    Clicks: 28,
    cost: "USD 600",
    company: "ZILLACON",
    conversions: "08",
    revenue: "$2,730.88",
  },
  {
    id: 6,
    Compaigns: " Hand Soap",
    Clicks: 32,
    cost: "USD 700",
    company: "SAVVY",
    conversions: "03",
    revenue: "$2,986.05",
  },
  {
    id: 7,
    Compaigns: " Dish Soap",
    Clicks: 36,
    cost: "USD 800",
    company: "BLEENDOT",
    conversions: "27",
    revenue: "$2,755.80",
  },
  {
    id: 8,
    Compaigns: " Sunscreen",
    Clicks: 40,
    cost: "USD 900",
    company: "UXMOX",
    conversions: "19",
    revenue: "$3,302.75",
  },
  {
    id: 9,
    Compaigns: " Shaving Cream ",
    Clicks: 26,
    cost: "USD 1000",
    company: "INCUBUS",
    conversions: "13",
    revenue: "$3,856.24",
  },
  {
    id: 10,
    Compaigns: "Razors ",
    Clicks: 28,
    cost: "USD 10",
    company: "AUSTEX",
    conversions: "26",
    revenue: "$3,668.64",
  },
  {
    id: 11,
    Compaigns: " Conditioner",
    Clicks: 35,
    cost: "USD 20",
    company: "ZILIDIUM",
    conversions: "19",
    revenue: "$1,987.14",
  },
  {
    id: 12,
    Compaigns: "Face Moisturizer ",
    Clicks: 39,
    cost: "USD 30",
    company: "ZOARERE",
    conversions: "16",
    revenue: "$1,795.31",
  },
  {
    id: 13,
    Compaigns: " Hand Sanitizer",
    Clicks: 33,
    cost: "USD 40",
    company: "COLAIRE",
    conversions: "19",
    revenue: "$2,396.73",
  },
  {
    id: 14,
    Compaigns: " Body Wash ",
    Clicks: 33,
    cost: "USD 50",
    company: "WEBIOTIC",
    conversions: "12",
    revenue: "$3,406.96",
  },
  {
    id: 15,
    Compaigns: " Mouthwash",
    Clicks: 25,
    cost: "USD 60",
    company: "ZBOO",
    conversions: "08",
    revenue: "$1,065.32",
  },
  {
    id: 16,
    Compaigns: "Tissues ",
    cost: "USD 70",
    company: "QUONK",
    conversions: "15",
    revenue: "$1,558.83",
  },
  {
    id: 17,
    Compaigns: "Hair Gel  ",
    cost: "USD 80",
    company: "IDEALIS",
    conversions: "31",
    revenue: "$1,848.84",
  },
  {
    id: 18,
    Compaigns: "Lip Balm ",
    cost: "USD 90",
    company: "DIGIGEN",
    conversions: "19",
    revenue: "$3,382.78",
  },
  {
    id: 19,
    Compaigns: "Shaving Razor  ",
    cost: "USD 120",
    company: "KONGENE",
    conversions: "09",
    revenue: "$1,668.05",
  },
  {
    id: 20,
    Compaigns: " Perfume",
    cost: "USD 130",
    company: "TROPOLIS",
    conversions: "28",
    revenue: "$2,730.21",
  },
  {
    id: 21,
    Compaigns: "Hair Styling Spray ",
    cost: "USD 149",
    company: "AVENETRO",
    conversions: "17",
    revenue: "$2,547.85",
  },
  {
    id: 22,
    Compaigns: " ",
    cost: "USD 150",
    company: "MALATHION",
    conversions: "08",
    revenue: "$3,538.05",
  },
  {
    id: 23,
    Compaigns: "Makeup Remover ",
    cost: "USD 160",
    company: "NETROPIC",
    conversions: "26",
    revenue: "$1,141.42",
  },
  {
    id: 24,
    Compaigns: " Acne Treatment",
    cost: "USD 170",
    company: "YURTURE",
    conversions: "11",
    revenue: "$2,877.89",
  },
  {
    id: 25,
    Compaigns: " Hair Mask ",
    cost: "USD 180",
    company: "TRIBALOG",
    conversions: "09",
    revenue: "$3,156.79",
  },
];

export const dataTableColumns = [
  {
    name: "Compaigns",
    selector: (row) => row.Compaigns,
    sortable: true,
  },
  {
    name: "Clicks",
    selector: (row) => row.Clicks,
    sortable: true,
    hide: 370,
  },
  {
    name: "Cost",
    selector: (row) => row.cost,
    sortable: true,
    hide: "sm",
  },
  {
    name: "Conversions",
    selector: (row) => row.conversions,
    sortable: true,
    hide: "sm",
  },
  {
    name: "Revenue",
    selector: (row) => row.revenue,
    sortable: true,
    hide: "md",
  },
];
